// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: testmsg.proto

#ifndef PROTOBUF_testmsg_2eproto__INCLUDED
#define PROTOBUF_testmsg_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace FVU {
class ChildMessage;
class ChildMessageDefaultTypeInternal;
extern ChildMessageDefaultTypeInternal _ChildMessage_default_instance_;
class TestMessage;
class TestMessageDefaultTypeInternal;
extern TestMessageDefaultTypeInternal _TestMessage_default_instance_;
}  // namespace FVU

namespace FVU {

namespace protobuf_testmsg_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_testmsg_2eproto

// ===================================================================

class ChildMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:FVU.ChildMessage) */ {
 public:
  ChildMessage();
  virtual ~ChildMessage();

  ChildMessage(const ChildMessage& from);

  inline ChildMessage& operator=(const ChildMessage& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ChildMessage& default_instance();

  static inline const ChildMessage* internal_default_instance() {
    return reinterpret_cast<const ChildMessage*>(
               &_ChildMessage_default_instance_);
  }

  void Swap(ChildMessage* other);

  // implements Message ----------------------------------------------

  inline ChildMessage* New() const PROTOBUF_FINAL { return New(NULL); }

  ChildMessage* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ChildMessage& from);
  void MergeFrom(const ChildMessage& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ChildMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // fixed32 FixedValue = 1;
  void clear_fixedvalue();
  static const int kFixedValueFieldNumber = 1;
  ::google::protobuf::uint32 fixedvalue() const;
  void set_fixedvalue(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:FVU.ChildMessage)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 fixedvalue_;
  mutable int _cached_size_;
  friend struct  protobuf_testmsg_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class TestMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:FVU.TestMessage) */ {
 public:
  TestMessage();
  virtual ~TestMessage();

  TestMessage(const TestMessage& from);

  inline TestMessage& operator=(const TestMessage& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TestMessage& default_instance();

  static inline const TestMessage* internal_default_instance() {
    return reinterpret_cast<const TestMessage*>(
               &_TestMessage_default_instance_);
  }

  void Swap(TestMessage* other);

  // implements Message ----------------------------------------------

  inline TestMessage* New() const PROTOBUF_FINAL { return New(NULL); }

  TestMessage* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const TestMessage& from);
  void MergeFrom(const TestMessage& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(TestMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .FVU.ChildMessage childMessage = 11;
  int childmessage_size() const;
  void clear_childmessage();
  static const int kChildMessageFieldNumber = 11;
  const ::FVU::ChildMessage& childmessage(int index) const;
  ::FVU::ChildMessage* mutable_childmessage(int index);
  ::FVU::ChildMessage* add_childmessage();
  ::google::protobuf::RepeatedPtrField< ::FVU::ChildMessage >*
      mutable_childmessage();
  const ::google::protobuf::RepeatedPtrField< ::FVU::ChildMessage >&
      childmessage() const;

  // string StringValue = 9;
  void clear_stringvalue();
  static const int kStringValueFieldNumber = 9;
  const ::std::string& stringvalue() const;
  void set_stringvalue(const ::std::string& value);
  #if LANG_CXX11
  void set_stringvalue(::std::string&& value);
  #endif
  void set_stringvalue(const char* value);
  void set_stringvalue(const char* value, size_t size);
  ::std::string* mutable_stringvalue();
  ::std::string* release_stringvalue();
  void set_allocated_stringvalue(::std::string* stringvalue);

  // bytes BytesValue = 10;
  void clear_bytesvalue();
  static const int kBytesValueFieldNumber = 10;
  const ::std::string& bytesvalue() const;
  void set_bytesvalue(const ::std::string& value);
  #if LANG_CXX11
  void set_bytesvalue(::std::string&& value);
  #endif
  void set_bytesvalue(const char* value);
  void set_bytesvalue(const void* value, size_t size);
  ::std::string* mutable_bytesvalue();
  ::std::string* release_bytesvalue();
  void set_allocated_bytesvalue(::std::string* bytesvalue);

  // double DoubleValue = 2;
  void clear_doublevalue();
  static const int kDoubleValueFieldNumber = 2;
  double doublevalue() const;
  void set_doublevalue(double value);

  // bool BoolValue = 1;
  void clear_boolvalue();
  static const int kBoolValueFieldNumber = 1;
  bool boolvalue() const;
  void set_boolvalue(bool value);

  // float FloatValue = 3;
  void clear_floatvalue();
  static const int kFloatValueFieldNumber = 3;
  float floatvalue() const;
  void set_floatvalue(float value);

  // int32 IntValue = 4;
  void clear_intvalue();
  static const int kIntValueFieldNumber = 4;
  ::google::protobuf::int32 intvalue() const;
  void set_intvalue(::google::protobuf::int32 value);

  // uint32 UIntValue = 5;
  void clear_uintvalue();
  static const int kUIntValueFieldNumber = 5;
  ::google::protobuf::uint32 uintvalue() const;
  void set_uintvalue(::google::protobuf::uint32 value);

  // int64 Int64Value = 6;
  void clear_int64value();
  static const int kInt64ValueFieldNumber = 6;
  ::google::protobuf::int64 int64value() const;
  void set_int64value(::google::protobuf::int64 value);

  // uint64 UInt64Value = 7;
  void clear_uint64value();
  static const int kUInt64ValueFieldNumber = 7;
  ::google::protobuf::uint64 uint64value() const;
  void set_uint64value(::google::protobuf::uint64 value);

  // sint32 SInt32Value = 8;
  void clear_sint32value();
  static const int kSInt32ValueFieldNumber = 8;
  ::google::protobuf::int32 sint32value() const;
  void set_sint32value(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:FVU.TestMessage)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::FVU::ChildMessage > childmessage_;
  ::google::protobuf::internal::ArenaStringPtr stringvalue_;
  ::google::protobuf::internal::ArenaStringPtr bytesvalue_;
  double doublevalue_;
  bool boolvalue_;
  float floatvalue_;
  ::google::protobuf::int32 intvalue_;
  ::google::protobuf::uint32 uintvalue_;
  ::google::protobuf::int64 int64value_;
  ::google::protobuf::uint64 uint64value_;
  ::google::protobuf::int32 sint32value_;
  mutable int _cached_size_;
  friend struct  protobuf_testmsg_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// ChildMessage

// fixed32 FixedValue = 1;
inline void ChildMessage::clear_fixedvalue() {
  fixedvalue_ = 0u;
}
inline ::google::protobuf::uint32 ChildMessage::fixedvalue() const {
  // @@protoc_insertion_point(field_get:FVU.ChildMessage.FixedValue)
  return fixedvalue_;
}
inline void ChildMessage::set_fixedvalue(::google::protobuf::uint32 value) {
  
  fixedvalue_ = value;
  // @@protoc_insertion_point(field_set:FVU.ChildMessage.FixedValue)
}

// -------------------------------------------------------------------

// TestMessage

// bool BoolValue = 1;
inline void TestMessage::clear_boolvalue() {
  boolvalue_ = false;
}
inline bool TestMessage::boolvalue() const {
  // @@protoc_insertion_point(field_get:FVU.TestMessage.BoolValue)
  return boolvalue_;
}
inline void TestMessage::set_boolvalue(bool value) {
  
  boolvalue_ = value;
  // @@protoc_insertion_point(field_set:FVU.TestMessage.BoolValue)
}

// double DoubleValue = 2;
inline void TestMessage::clear_doublevalue() {
  doublevalue_ = 0;
}
inline double TestMessage::doublevalue() const {
  // @@protoc_insertion_point(field_get:FVU.TestMessage.DoubleValue)
  return doublevalue_;
}
inline void TestMessage::set_doublevalue(double value) {
  
  doublevalue_ = value;
  // @@protoc_insertion_point(field_set:FVU.TestMessage.DoubleValue)
}

// float FloatValue = 3;
inline void TestMessage::clear_floatvalue() {
  floatvalue_ = 0;
}
inline float TestMessage::floatvalue() const {
  // @@protoc_insertion_point(field_get:FVU.TestMessage.FloatValue)
  return floatvalue_;
}
inline void TestMessage::set_floatvalue(float value) {
  
  floatvalue_ = value;
  // @@protoc_insertion_point(field_set:FVU.TestMessage.FloatValue)
}

// int32 IntValue = 4;
inline void TestMessage::clear_intvalue() {
  intvalue_ = 0;
}
inline ::google::protobuf::int32 TestMessage::intvalue() const {
  // @@protoc_insertion_point(field_get:FVU.TestMessage.IntValue)
  return intvalue_;
}
inline void TestMessage::set_intvalue(::google::protobuf::int32 value) {
  
  intvalue_ = value;
  // @@protoc_insertion_point(field_set:FVU.TestMessage.IntValue)
}

// uint32 UIntValue = 5;
inline void TestMessage::clear_uintvalue() {
  uintvalue_ = 0u;
}
inline ::google::protobuf::uint32 TestMessage::uintvalue() const {
  // @@protoc_insertion_point(field_get:FVU.TestMessage.UIntValue)
  return uintvalue_;
}
inline void TestMessage::set_uintvalue(::google::protobuf::uint32 value) {
  
  uintvalue_ = value;
  // @@protoc_insertion_point(field_set:FVU.TestMessage.UIntValue)
}

// int64 Int64Value = 6;
inline void TestMessage::clear_int64value() {
  int64value_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 TestMessage::int64value() const {
  // @@protoc_insertion_point(field_get:FVU.TestMessage.Int64Value)
  return int64value_;
}
inline void TestMessage::set_int64value(::google::protobuf::int64 value) {
  
  int64value_ = value;
  // @@protoc_insertion_point(field_set:FVU.TestMessage.Int64Value)
}

// uint64 UInt64Value = 7;
inline void TestMessage::clear_uint64value() {
  uint64value_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 TestMessage::uint64value() const {
  // @@protoc_insertion_point(field_get:FVU.TestMessage.UInt64Value)
  return uint64value_;
}
inline void TestMessage::set_uint64value(::google::protobuf::uint64 value) {
  
  uint64value_ = value;
  // @@protoc_insertion_point(field_set:FVU.TestMessage.UInt64Value)
}

// sint32 SInt32Value = 8;
inline void TestMessage::clear_sint32value() {
  sint32value_ = 0;
}
inline ::google::protobuf::int32 TestMessage::sint32value() const {
  // @@protoc_insertion_point(field_get:FVU.TestMessage.SInt32Value)
  return sint32value_;
}
inline void TestMessage::set_sint32value(::google::protobuf::int32 value) {
  
  sint32value_ = value;
  // @@protoc_insertion_point(field_set:FVU.TestMessage.SInt32Value)
}

// string StringValue = 9;
inline void TestMessage::clear_stringvalue() {
  stringvalue_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& TestMessage::stringvalue() const {
  // @@protoc_insertion_point(field_get:FVU.TestMessage.StringValue)
  return stringvalue_.GetNoArena();
}
inline void TestMessage::set_stringvalue(const ::std::string& value) {
  
  stringvalue_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:FVU.TestMessage.StringValue)
}
#if LANG_CXX11
inline void TestMessage::set_stringvalue(::std::string&& value) {
  
  stringvalue_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:FVU.TestMessage.StringValue)
}
#endif
inline void TestMessage::set_stringvalue(const char* value) {
  
  stringvalue_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:FVU.TestMessage.StringValue)
}
inline void TestMessage::set_stringvalue(const char* value, size_t size) {
  
  stringvalue_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:FVU.TestMessage.StringValue)
}
inline ::std::string* TestMessage::mutable_stringvalue() {
  
  // @@protoc_insertion_point(field_mutable:FVU.TestMessage.StringValue)
  return stringvalue_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* TestMessage::release_stringvalue() {
  // @@protoc_insertion_point(field_release:FVU.TestMessage.StringValue)
  
  return stringvalue_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TestMessage::set_allocated_stringvalue(::std::string* stringvalue) {
  if (stringvalue != NULL) {
    
  } else {
    
  }
  stringvalue_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), stringvalue);
  // @@protoc_insertion_point(field_set_allocated:FVU.TestMessage.StringValue)
}

// bytes BytesValue = 10;
inline void TestMessage::clear_bytesvalue() {
  bytesvalue_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& TestMessage::bytesvalue() const {
  // @@protoc_insertion_point(field_get:FVU.TestMessage.BytesValue)
  return bytesvalue_.GetNoArena();
}
inline void TestMessage::set_bytesvalue(const ::std::string& value) {
  
  bytesvalue_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:FVU.TestMessage.BytesValue)
}
#if LANG_CXX11
inline void TestMessage::set_bytesvalue(::std::string&& value) {
  
  bytesvalue_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:FVU.TestMessage.BytesValue)
}
#endif
inline void TestMessage::set_bytesvalue(const char* value) {
  
  bytesvalue_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:FVU.TestMessage.BytesValue)
}
inline void TestMessage::set_bytesvalue(const void* value, size_t size) {
  
  bytesvalue_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:FVU.TestMessage.BytesValue)
}
inline ::std::string* TestMessage::mutable_bytesvalue() {
  
  // @@protoc_insertion_point(field_mutable:FVU.TestMessage.BytesValue)
  return bytesvalue_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* TestMessage::release_bytesvalue() {
  // @@protoc_insertion_point(field_release:FVU.TestMessage.BytesValue)
  
  return bytesvalue_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TestMessage::set_allocated_bytesvalue(::std::string* bytesvalue) {
  if (bytesvalue != NULL) {
    
  } else {
    
  }
  bytesvalue_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), bytesvalue);
  // @@protoc_insertion_point(field_set_allocated:FVU.TestMessage.BytesValue)
}

// repeated .FVU.ChildMessage childMessage = 11;
inline int TestMessage::childmessage_size() const {
  return childmessage_.size();
}
inline void TestMessage::clear_childmessage() {
  childmessage_.Clear();
}
inline const ::FVU::ChildMessage& TestMessage::childmessage(int index) const {
  // @@protoc_insertion_point(field_get:FVU.TestMessage.childMessage)
  return childmessage_.Get(index);
}
inline ::FVU::ChildMessage* TestMessage::mutable_childmessage(int index) {
  // @@protoc_insertion_point(field_mutable:FVU.TestMessage.childMessage)
  return childmessage_.Mutable(index);
}
inline ::FVU::ChildMessage* TestMessage::add_childmessage() {
  // @@protoc_insertion_point(field_add:FVU.TestMessage.childMessage)
  return childmessage_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::FVU::ChildMessage >*
TestMessage::mutable_childmessage() {
  // @@protoc_insertion_point(field_mutable_list:FVU.TestMessage.childMessage)
  return &childmessage_;
}
inline const ::google::protobuf::RepeatedPtrField< ::FVU::ChildMessage >&
TestMessage::childmessage() const {
  // @@protoc_insertion_point(field_list:FVU.TestMessage.childMessage)
  return childmessage_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace FVU

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_testmsg_2eproto__INCLUDED
